
spring:
  datasource:
    url: jdbc:postgresql://postgres.dzcode:5432/dzcode
    username: postgres
    password: password
  jpa:
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: create
